### ISSUE TITLE
Role is not declared in Ansible Galaxy

### ISSUE THREAD

**Issue by amenophis** [Elao/ansible-role-phpmyadmin#1]
Hi,
It seems that this role is not declared in Ansible Galaxy.
Is it normal ?

**Comment by nervo** [comment]
Yep, we are just in a freeze-before-refactoring state :)
We don't really want to officially share this role before it's done.

Thanks for your interest

**Comment by amenophis** [comment]
OK perfect,
Any idea when it will be done ?

**Comment by nervo** [comment]
2 or 3 weeks, i guess :)

**Comment by amenophis** [comment]
OK perfect.
Will use it locally for the moment,

**Comment by nervo** [comment]
Good :)
